import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "@/utils/fonts";
import { Toaster } from "@/components/ui/toaster";
import NextAuthSessionProvider from "@/providers/SessionProvider";

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang='pt-BR'>
   <NextAuthSessionProvider>
    <body className={`${roboto.className} h-screen bg-black`}>
     <main className='h-full w-full'>{children}</main>
     <Toaster />
    </body>
   </NextAuthSessionProvider>
  </html>
 );
}
