import type { Metadata } from "next";
import "./globals.css";
import { roboto } from "@/utils/fonts";
import NextAuthSessionProvider from "@/providers/SessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <NextAuthSessionProvider>
        <body className={`${roboto.className} bg-black h-screen`}>
          <main className="w-full h-full">{children}</main>
        </body>
      </NextAuthSessionProvider>
    </html>
  );
}
